/*
* Generated by XIV.Core.Utils.ClassGenerator
*/
using UnityEngine;

public static class AnimationConstants
{
	// Inner Classes
	public static class ArcherController
	{
		// Inner Classes
		public static class Clips
		{
			// Members
			public const string ArcherController_Aim_Idle = "Aim_Idle";
			public static readonly int ArcherController_Aim_IdleHash = Animator.StringToHash("Aim_Idle");
			public const string ArcherController_Release = "Release";
			public static readonly int ArcherController_ReleaseHash = Animator.StringToHash("Release");
			public const string ArcherController_Draw_Arrow = "Draw_Arrow";
			public static readonly int ArcherController_Draw_ArrowHash = Animator.StringToHash("Draw_Arrow");
			public const string ArcherController_Idle = "Idle";
			public static readonly int ArcherController_IdleHash = Animator.StringToHash("Idle");
			
		} // class Clips
		
		public static class Parameters
		{
			// Members
			public const string ArcherController_State_Int = "State";
			public static readonly int ArcherController_State_IntID = Animator.StringToHash("State");
			
		} // class Parameters
		
		public static class Layers
		{
			// Members
			public const int ArcherController_Base_Layer = 0;
			
		} // class Layers
		
		
	} // class ArcherController
	
	
} // class AnimationConstants
